---
# If set to true, the minishift role is first executed to setup a proper VM for installing Istio locally
run_minishift_role: false

istio:

  # Could be a tag "0.2.12, 0.3.0, 0.4.0" version or be empty "", then in this case, the latest release will be downloaded
  release_tag_name: "0.4.0"

  # Folder where you want to install the distro on your machine. By default, we will install it here ~/.istio
  dest: "~/.istio"

  # Install istio with or without istio-auth module
  auth: false

  addon:
    - "grafana"
    - "prometheus"
    - "servicegraph"
    - "zipkin"

  # Whether or not Jaeger should be installed as well
  jaeger: false

  # Whether or not the Bookinfo showcase should be installed as well
  bookinfo: false

  # Whether or not to open apps in the browser
  open_apps: false